name: Stable Release

on:
  push:
    branches:
      - main

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Dependencies
        run: |
          pip install --user poetry && poetry install
      - name: Publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
